package bybit

// TimeInForcePerp :
type TimeInForcePerp string

const (
	// TimeInForcePerpGTC :
	TimeInForcePerpGTC = TimeInForcePerp("GTC")
	// TimeInForcePerpFOK :
	TimeInForcePerpFOK = TimeInForcePerp("FOK")
	// TimeInForcePerpIOC :
	TimeInForcePerpIOC = TimeInForcePerp("IOC")
)

// PerpInterval :
type PerpInterval string

const (
	// PerpInterval1m :
	PerpInterval1m = Interval("1m")
	// PerpInterval3m :
	PerpInterval3m = Interval("3m")
	// PerpInterval5m :
	PerpInterval5m = Interval("5m")
	// PerpInterval15m :
	PerpInterval15m = Interval("15m")
	// PerpInterval30m :
	PerpInterval30m = Interval("30m")
	// PerpInterval1h :
	PerpInterval1h = Interval("1h")
	// PerpInterval2h :
	PerpInterval2h = Interval("2h")
	// PerpInterval4h :
	PerpInterval4h = Interval("4h")
	// PerpInterval6h :
	PerpInterval6h = Interval("6h")
	// PerpInterval12h :
	PerpInterval12h = Interval("12h")
	// PerpInterval1d :
	PerpInterval1d = Interval("1d")
	// PerpInterval1w :
	PerpInterval1w = Interval("1w")
	// PerpInterval1M :
	PerpInterval1M = Interval("1M")
)

// OrderTypePerp :
type OrderTypePerp string

const (
	// OrderTypePerpLimit :
	OrderTypePerpLimit = OrderTypePerp("LIMIT")
	// OrderTypePerpMarket :
	OrderTypePerpMarket = OrderTypePerp("MARKET")
	// OrderTypePerpLimitMaker :
	OrderTypePerpLimitMaker = OrderTypePerp("LIMIT_MAKER")
)

// OrderStatusPerp :
type OrderStatusPerp string

const (
	// OrderStatusPerpNew :
	OrderStatusPerpNew = OrderStatusPerp("NEW")
	// OrderStatusPerpPartiallyFilled :
	OrderStatusPerpPartiallyFilled = OrderStatusPerp("PARTIALLY_FILLED")
	// OrderStatusPerpFilled :
	OrderStatusPerpFilled = OrderStatusPerp("FILLED")
	// OrderStatusPerpCanceled :
	OrderStatusPerpCanceled = OrderStatusPerp("CANCELED")
	// OrderStatusPerpPendingCancel :
	OrderStatusPerpPendingCancel = OrderStatusPerp("PENDING_CANCEL")
	// OrderStatusPerpPendingNew :
	OrderStatusPerpPendingNew = OrderStatusPerp("PENDING_NEW")
	// OrderStatusPerpRejected :
	OrderStatusPerpRejected = OrderStatusPerp("REJECTED")
)

// SymbolPerp :
type SymbolPerp string

const (
	// SymbolPerpBTCUSDT :
	SymbolPerpBTCUSDT = SymbolPerp("BTCUSDT")
	// SymbolPerpETHUSDT :
	SymbolPerpETHUSDT = SymbolPerp("ETHUSDT")
	// SymbolPerpEOSUSDT :
	SymbolPerpEOSUSDT = SymbolPerp("EOSUSDT")
	// SymbolPerpNEOBTC :
	SymbolPerpNEOBTC = SymbolPerp("NEOBTC")
	// SymbolPerpXRPUSDT :
	SymbolPerpXRPUSDT = SymbolPerp("XRPUSDT")
	// SymbolPerpUNIUSDT :
	SymbolPerpUNIUSDT = SymbolPerp("UNIUSDT")
	// SymbolPerpUNIBTC :
	SymbolPerpUNIBTC = SymbolPerp("UNIBTC")
	// SymbolPerpDOTUSDT :
	SymbolPerpDOTUSDT = SymbolPerp("DOTUSDT")
	// SymbolPerpETHBTC :
	SymbolPerpETHBTC = SymbolPerp("ETHBTC")
	// SymbolPerpEOSETH :
	SymbolPerpEOSETH = SymbolPerp("EOSETH")
	// SymbolPerpBTCETH :
	SymbolPerpBTCETH = SymbolPerp("BTCETH")
	// SymbolPerpBTTUSDT :
	SymbolPerpBTTUSDT = SymbolPerp("BTTUSDT")
	// SymbolPerpXLMUSDT :
	SymbolPerpXLMUSDT = SymbolPerp("XLMUSDT")
	// SymbolPerpLTCUSDT :
	SymbolPerpLTCUSDT = SymbolPerp("LTCUSDT")
	// SymbolPerpXRPBTC :
	SymbolPerpXRPBTC = SymbolPerp("XRPBTC")
	// SymbolPerpXRPEOS :
	SymbolPerpXRPEOS = SymbolPerp("XRPEOS")
	// SymbolPerpDOGEUSDT :
	SymbolPerpDOGEUSDT = SymbolPerp("DOGEUSDT")
	// SymbolPerpBITUSDT :
	SymbolPerpBITUSDT = SymbolPerp("BITUSDT")
	// SymbolPerpADAUSDT :
	SymbolPerpADAUSDT = SymbolPerp("ADAUSDT")
	// SymbolPerpXTZUSDT :
	SymbolPerpXTZUSDT = SymbolPerp("XTZUSDT")
	// SymbolPerpAXSUSDT :
	SymbolPerpAXSUSDT = SymbolPerp("AXSUSDT")
	// SymbolPerpDYDXUSDT :
	SymbolPerpDYDXUSDT = SymbolPerp("DYDXUSDT")
	// SymbolPerpPMTEST2USDT :
	SymbolPerpPMTEST2USDT = SymbolPerp("PMTEST2USDT")
	// SymbolPerpPERPUSDT :
	SymbolPerpPERPUSDT = SymbolPerp("PERPUSDT")
	// SymbolPerpGRTUSDT :
	SymbolPerpGRTUSDT = SymbolPerp("GRTUSDT")
	// SymbolPerpUSDCUSDT :
	SymbolPerpUSDCUSDT = SymbolPerp("USDCUSDT")
	// SymbolPerpSOLUSDT :
	SymbolPerpSOLUSDT = SymbolPerp("SOLUSDT")
	// SymbolPerpOMGUSDT :
	SymbolPerpOMGUSDT = SymbolPerp("OMGUSDT")
	// SymbolPerpLUNCUSDT :
	SymbolPerpLUNCUSDT = SymbolPerp("LUNCUSDT")
	// SymbolPerpPMTEST15USDT :
	SymbolPerpPMTEST15USDT = SymbolPerp("PMTEST15USDT")
	// SymbolPerpICPETH :
	SymbolPerpICPETH = SymbolPerp("ICPETH")
	// SymbolPerpPMTEST7ETH :
	SymbolPerpPMTEST7ETH = SymbolPerp("PMTEST7ETH")
	// SymbolPerpBTCUSDC :
	SymbolPerpBTCUSDC = SymbolPerp("BTCUSDC")
	// SymbolPerpETHUSDC :
	SymbolPerpETHUSDC = SymbolPerp("ETHUSDC")
	// SymbolPerpBITETH :
	SymbolPerpBITETH = SymbolPerp("BITETH")
	// SymbolPerpPMTEST8PMTEST7 :
	SymbolPerpPMTEST8PMTEST7 = SymbolPerp("PMTEST8PMTEST7")
	// SymbolPerpPMTEST7USDC :
	SymbolPerpPMTEST7USDC = SymbolPerp("PMTEST7USDC")
	// SymbolPerpPMTEST8USDC :
	SymbolPerpPMTEST8USDC = SymbolPerp("PMTEST8USDC")
	// SymbolPerpUSDTBIT :
	SymbolPerpUSDTBIT = SymbolPerp("USDTBIT")
	// SymbolPerpXRP3LUSDT :
	SymbolPerpXRP3LUSDT = SymbolPerp("XRP3LUSDT")
	// SymbolPerpXRP3SUSDT :
	SymbolPerpXRP3SUSDT = SymbolPerp("XRP3SUSDT")
	// SymbolPerpUNIBIT :
	SymbolPerpUNIBIT = SymbolPerp("UNIBIT")
	// SymbolPerpUSDTTESTNETCS1 :
	SymbolPerpUSDTTESTNETCS1 = SymbolPerp("USDTTESTNETCS1")
	// SymbolPerpDONNYTESTUSDT :
	SymbolPerpDONNYTESTUSDT = SymbolPerp("DONNYTESTUSDT")
	// SymbolPerpEOSBIT :
	SymbolPerpEOSBIT = SymbolPerp("EOSBIT")
	// SymbolPerpXLMQQT :
	SymbolPerpXLMQQT = SymbolPerp("XLMQQT")
	// SymbolPerpLTCXLM :
	SymbolPerpLTCXLM = SymbolPerp("LTCXLM")
	// SymbolPerpXLMEOS :
	SymbolPerpXLMEOS = SymbolPerp("XLMEOS")
	// SymbolPerpXLMXRP :
	SymbolPerpXLMXRP = SymbolPerp("XLMXRP")
	// SymbolPerpXLMSHIBI :
	SymbolPerpXLMSHIBI = SymbolPerp("XLMSHIBI")
	// SymbolPerpXLMTRX :
	SymbolPerpXLMTRX = SymbolPerp("XLMTRX")
	// SymbolPerpXLMMFT :
	SymbolPerpXLMMFT = SymbolPerp("XLMMFT")
	// SymbolPerpXLMQTHQ :
	SymbolPerpXLMQTHQ = SymbolPerp("XLMQTHQ")
	// SymbolPerpXLMNEO :
	SymbolPerpXLMNEO = SymbolPerp("XLMNEO")
	// SymbolPerpUNILTC :
	SymbolPerpUNILTC = SymbolPerp("UNILTC")
	// SymbolPerpUNINEO :
	SymbolPerpUNINEO = SymbolPerp("UNINEO")
	// SymbolPerpBTC3SUSDT :
	SymbolPerpBTC3SUSDT = SymbolPerp("BTC3SUSDT")
	// SymbolPerpBTC3LUSDT :
	SymbolPerpBTC3LUSDT = SymbolPerp("BTC3LUSDT")
	// SymbolPerpQTHQQQT :
	SymbolPerpQTHQQQT = SymbolPerp("QTHQQQT")
	// SymbolPerpETH3LUSDT :
	SymbolPerpETH3LUSDT = SymbolPerp("ETH3LUSDT")
	// SymbolPerpSPOTTEST3USDT :
	SymbolPerpSPOTTEST3USDT = SymbolPerp("SPOTTEST3USDT")
	// SymbolPerpPMTEST12ETH :
	SymbolPerpPMTEST12ETH = SymbolPerp("PMTEST12ETH")
	// SymbolPerpPMTEST12UST :
	SymbolPerpPMTEST12UST = SymbolPerp("PMTEST12UST")
	// SymbolPerpUSDTUST :
	SymbolPerpUSDTUST = SymbolPerp("USDTUST")
	// SymbolPerpPMTEST12DAI :
	SymbolPerpPMTEST12DAI = SymbolPerp("PMTEST12DAI")
	// SymbolPerpUSDTDAI :
	SymbolPerpUSDTDAI = SymbolPerp("USDTDAI")
	// SymbolPerpXXXXYFI :
	SymbolPerpXXXXYFI = SymbolPerp("XXXXYFI")
	// SymbolPerpUSTCUSDT :
	SymbolPerpUSTCUSDT = SymbolPerp("USTCUSDT")
	// SymbolPerpDONNYTEST02USDT :
	SymbolPerpDONNYTEST02USDT = SymbolPerp("DONNYTEST02USDT")
	// SymbolPerpPMTEST047USDT :
	SymbolPerpPMTEST047USDT = SymbolPerp("PMTEST047USDT")
	// SymbolPerpPMTESTAUSDT :
	SymbolPerpPMTESTAUSDT = SymbolPerp("PMTESTAUSDT")
	// SymbolPerpXRPBIT :
	SymbolPerpXRPBIT = SymbolPerp("XRPBIT")
	// SymbolPerpPMTESTCUSDT :
	SymbolPerpPMTESTCUSDT = SymbolPerp("PMTESTCUSDT")
	// SymbolPerpPMTESTZUSDT :
	SymbolPerpPMTESTZUSDT = SymbolPerp("PMTESTZUSDT")
	// SymbolPerpPMTESTBUSDT :
	SymbolPerpPMTESTBUSDT = SymbolPerp("PMTESTBUSDT")
	// SymbolPerpPMTESTDUSDT :
	SymbolPerpPMTESTDUSDT = SymbolPerp("PMTESTDUSDT")
	// SymbolPerpPMTESTABTC :
	SymbolPerpPMTESTABTC = SymbolPerp("PMTESTABTC")
	// SymbolPerpDYDXETH :
	SymbolPerpDYDXETH = SymbolPerp("DYDXETH")
	// SymbolPerpDYDXQQT :
	SymbolPerpDYDXQQT = SymbolPerp("DYDXQQT")
	// SymbolPerpNEODYDX :
	SymbolPerpNEODYDX = SymbolPerp("NEODYDX")
	// SymbolPerpDYDXXRP :
	SymbolPerpDYDXXRP = SymbolPerp("DYDXXRP")
	// SymbolPerpEOSDYDX :
	SymbolPerpEOSDYDX = SymbolPerp("EOSDYDX")
	// SymbolPerpDYDXNEO :
	SymbolPerpDYDXNEO = SymbolPerp("DYDXNEO")
	// SymbolPerpDYDXDOGE :
	SymbolPerpDYDXDOGE = SymbolPerp("DYDXDOGE")
	// SymbolPerpDOGEDYDX :
	SymbolPerpDOGEDYDX = SymbolPerp("DOGEDYDX")
	// SymbolPerpMFTDYDX :
	SymbolPerpMFTDYDX = SymbolPerp("MFTDYDX")
	// SymbolPerpXRPDYDX :
	SymbolPerpXRPDYDX = SymbolPerp("XRPDYDX")
	// SymbolPerpETHDYDX :
	SymbolPerpETHDYDX = SymbolPerp("ETHDYDX")
	// SymbolPerpQQTDYDX :
	SymbolPerpQQTDYDX = SymbolPerp("QQTDYDX")
	// SymbolPerpDYDXPIG :
	SymbolPerpDYDXPIG = SymbolPerp("DYDXPIG")
	// SymbolPerpQQTHT :
	SymbolPerpQQTHT = SymbolPerp("QQTHT")
	// SymbolPerpEOSHT :
	SymbolPerpEOSHT = SymbolPerp("EOSHT")
	// SymbolPerpHTQQT :
	SymbolPerpHTQQT = SymbolPerp("HTQQT")
	// SymbolPerpHTEOS :
	SymbolPerpHTEOS = SymbolPerp("HTEOS")
	// SymbolPerpMVUSDT :
	SymbolPerpMVUSDT = SymbolPerp("MVUSDT")
	// SymbolPerpBTCBIT :
	SymbolPerpBTCBIT = SymbolPerp("BTCBIT")
	// SymbolPerpPMTESTEUSDT :
	SymbolPerpPMTESTEUSDT = SymbolPerp("PMTESTEUSDT")
	// SymbolPerpPMTEST2USDC :
	SymbolPerpPMTEST2USDC = SymbolPerp("PMTEST2USDC")
	// SymbolPerpPMTEST6USDC :
	SymbolPerpPMTEST6USDC = SymbolPerp("PMTEST6USDC")
	// SymbolPerpADAUSDC :
	SymbolPerpADAUSDC = SymbolPerp("ADAUSDC")
	// SymbolPerpUSDTTEST :
	SymbolPerpUSDTTEST = SymbolPerp("USDTTEST")
	// SymbolPerpBTCTEST :
	SymbolPerpBTCTEST = SymbolPerp("BTCTEST")
	// SymbolPerpPMTEST12USDT :
	SymbolPerpPMTEST12USDT = SymbolPerp("PMTEST12USDT")
	// SymbolPerpPMTEST12BTC :
	SymbolPerpPMTEST12BTC = SymbolPerp("PMTEST12BTC")
	// SymbolPerpPORTUGALUSDT :
	SymbolPerpPORTUGALUSDT = SymbolPerp("PORTUGALUSDT")
	// SymbolPerpEOS3LUSDT :
	SymbolPerpEOS3LUSDT = SymbolPerp("EOS3LUSDT")
	// SymbolPerpGRPCUSDT :
	SymbolPerpGRPCUSDT = SymbolPerp("GRPCUSDT")
	// SymbolPerpGRPCBTC :
	SymbolPerpGRPCBTC = SymbolPerp("GRPCBTC")
	// SymbolPerpUSDTETH :
	SymbolPerpUSDTETH = SymbolPerp("USDTETH")
	// SymbolPerpGRPCETH :
	SymbolPerpGRPCETH = SymbolPerp("GRPCETH")
	// SymbolPerpPORTUGALEOS :
	SymbolPerpPORTUGALEOS = SymbolPerp("PORTUGALEOS")
	// SymbolPerpPMTEST03EOS :
	SymbolPerpPMTEST03EOS = SymbolPerp("PMTEST03EOS")
	// SymbolPerpPMTEST03ETH :
	SymbolPerpPMTEST03ETH = SymbolPerp("PMTEST03ETH")
	// SymbolPerpPMTEST03XRP :
	SymbolPerpPMTEST03XRP = SymbolPerp("PMTEST03XRP")
	// SymbolPerpDFGUSDT :
	SymbolPerpDFGUSDT = SymbolPerp("DFGUSDT")
	// SymbolPerpLANG1ETH :
	SymbolPerpLANG1ETH = SymbolPerp("LANG1ETH")
	// SymbolPerpSOLOETH :
	SymbolPerpSOLOETH = SymbolPerp("SOLOETH")
	// SymbolPerpSOLOUSDT :
	SymbolPerpSOLOUSDT = SymbolPerp("SOLOUSDT")
	// SymbolPerpWERUSDT :
	SymbolPerpWERUSDT = SymbolPerp("WERUSDT")
	// SymbolPerpTESTTUSDT :
	SymbolPerpTESTTUSDT = SymbolPerp("TESTTUSDT")
	// SymbolPerpSOL3SUSDT :
	SymbolPerpSOL3SUSDT = SymbolPerp("SOL3SUSDT")
	// SymbolPerpSOL3LUSDT :
	SymbolPerpSOL3LUSDT = SymbolPerp("SOL3LUSDT")
	// SymbolPerpAAVEBTC :
	SymbolPerpAAVEBTC = SymbolPerp("AAVEBTC")
	// SymbolPerpXLMBTC :
	SymbolPerpXLMBTC = SymbolPerp("XLMBTC")
	// SymbolPerpLTCBTC :
	SymbolPerpLTCBTC = SymbolPerp("LTCBTC")
	// SymbolPerpPMTEST16USDT :
	SymbolPerpPMTEST16USDT = SymbolPerp("PMTEST16USDT")
	// SymbolPerpFFFFUSDT :
	SymbolPerpFFFFUSDT = SymbolPerp("FFFFUSDT")
	// SymbolPerpPORTUGALETH :
	SymbolPerpPORTUGALETH = SymbolPerp("PORTUGALETH")
	// SymbolPerpZENUSDT :
	SymbolPerpZENUSDT = SymbolPerp("ZENUSDT")
	// SymbolPerpSOS3LBTC :
	SymbolPerpSOS3LBTC = SymbolPerp("SOS3LBTC")
	// SymbolPerpSOS3SUSDT :
	SymbolPerpSOS3SUSDT = SymbolPerp("SOS3SUSDT")
	// SymbolPerpSOS3LUSDT :
	SymbolPerpSOS3LUSDT = SymbolPerp("SOS3LUSDT")
	// SymbolPerpICXUSDT :
	SymbolPerpICXUSDT = SymbolPerp("ICXUSDT")
	// SymbolPerpSTXUSDT :
	SymbolPerpSTXUSDT = SymbolPerp("STXUSDT")
	// SymbolPerpSOLBIT :
	SymbolPerpSOLBIT = SymbolPerp("SOLBIT")
	// SymbolPerpPMTEST001USDT :
	SymbolPerpPMTEST001USDT = SymbolPerp("PMTEST001USDT")
	// SymbolPerpSOLEOS :
	SymbolPerpSOLEOS = SymbolPerp("SOLEOS")
	// SymbolPerpTRIBLUSDT :
	SymbolPerpTRIBLUSDT = SymbolPerp("TRIBLUSDT")
	// SymbolPerpBTGETH :
	SymbolPerpBTGETH = SymbolPerp("BTGETH")
	// SymbolPerpAVAXUSDT :
	SymbolPerpAVAXUSDT = SymbolPerp("AVAXUSDT")
	// SymbolPerpSANDUSDT :
	SymbolPerpSANDUSDT = SymbolPerp("SANDUSDT")
	// SymbolPerpBTGUSDC :
	SymbolPerpBTGUSDC = SymbolPerp("BTGUSDC")
	// SymbolPerpBTGBIT :
	SymbolPerpBTGBIT = SymbolPerp("BTGBIT")
	// SymbolPerpBTTETH :
	SymbolPerpBTTETH = SymbolPerp("BTTETH")
	// SymbolPerpBUSDUSDT :
	SymbolPerpBUSDUSDT = SymbolPerp("BUSDUSDT")
	// SymbolPerpNEOEOS :
	SymbolPerpNEOEOS = SymbolPerp("NEOEOS")
	// SymbolPerpHNTUSDT :
	SymbolPerpHNTUSDT = SymbolPerp("HNTUSDT")
	// SymbolPerpNEOETH :
	SymbolPerpNEOETH = SymbolPerp("NEOETH")
	// SymbolPerpUNIETH :
	SymbolPerpUNIETH = SymbolPerp("UNIETH")
	// SymbolPerpLUNCEOS :
	SymbolPerpLUNCEOS = SymbolPerp("LUNCEOS")
	// SymbolPerpLUNCXRP :
	SymbolPerpLUNCXRP = SymbolPerp("LUNCXRP")
	// SymbolPerpNEOBIT :
	SymbolPerpNEOBIT = SymbolPerp("NEOBIT")
	// SymbolPerpDOGEBRL :
	SymbolPerpDOGEBRL = SymbolPerp("DOGEBRL")
	// SymbolPerpBRLUSDT :
	SymbolPerpBRLUSDT = SymbolPerp("BRLUSDT")
	// SymbolPerpSOLUSD :
	SymbolPerpSOLUSD = SymbolPerp("SOLUSD")
	// SymbolPerpUSDEUR :
	SymbolPerpUSDEUR = SymbolPerp("USDEUR")
	// SymbolPerpUSDTEUR :
	SymbolPerpUSDTEUR = SymbolPerp("USDTEUR")
	// SymbolPerpUSDTUSD :
	SymbolPerpUSDTUSD = SymbolPerp("USDTUSD")
	// SymbolPerpSOLUSDC :
	SymbolPerpSOLUSDC = SymbolPerp("SOLUSDC")
	// SymbolPerpDOTUSDC :
	SymbolPerpDOTUSDC = SymbolPerp("DOTUSDC")
	// SymbolPerpXRPUSDC :
	SymbolPerpXRPUSDC = SymbolPerp("XRPUSDC")
	// SymbolPerpBITUSDC :
	SymbolPerpBITUSDC = SymbolPerp("BITUSDC")
	// SymbolPerpPMTEST15BTC :
	SymbolPerpPMTEST15BTC = SymbolPerp("PMTEST15BTC")
	// SymbolPerpDCRUSDT :
	SymbolPerpDCRUSDT = SymbolPerp("DCRUSDT")
	// SymbolPerpEOSDAI :
	SymbolPerpEOSDAI = SymbolPerp("EOSDAI")
	// SymbolPerpSHIBIDAI :
	SymbolPerpSHIBIDAI = SymbolPerp("SHIBIDAI")
)
